id: I96EFC72A
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-24T15:50:03+00:00'
last_modified: '2022-06-10T08:52:42.264165+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W2PD17096
  title: ཡོན་ཏན་མཛོད་ཀྱི་འགྲེལ་པ་ཉི་ཟླའི་སྒྲོན་མེ། རྩྭ་ར་མཁན་པོ་ཆོས་གྲགས་ཀྱི་མཆན་ཅན།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    F5A9:
      image_group_id: I3PD880
      title: Volume 1 of yon tan mdzod kyi ʼgrel pa nyi zlaʼi sgron me/ rtsw ra mkhan
        po chos grags kyi mchan can/
      total_pages: 778
      order: 1
      base_file: F5A9.txt
    944D:
      image_group_id: I3PD881
      title: Volume 2 of yon tan mdzod kyi ʼgrel pa nyi zlaʼi sgron me/ rtsw ra mkhan
        po chos grags kyi mchan can/
      total_pages: 638
      order: 2
      base_file: 944D.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
